<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login Test Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>2</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>023f87ae-6838-480f-99cc-fcb13a78b8d8</testSuiteGuid>
   <testCaseLink>
      <guid>55a58551-1063-44eb-b087-7ce0105aa318</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/1. Login with valid username and password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f40a5dab-84a8-4926-a668-551dec9e7e18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36503804-6122-4055-a450-f8ca058cb28e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5910e5aa-c831-44c9-922a-559cc129c293</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/2. Login with incorrect username and incorrect password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>906a57d6-9ad1-4c37-b00e-cad12cf72b20</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eeea80d3-c8af-439f-a5d5-aecf27a3b8fe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>29f289ef-1df4-41d6-b703-5881125111f0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/3. Login with correct username and empty password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6a4a9be-ba63-4cd9-818c-46f9e32caf32</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf6efbc8-47fc-4cd5-a5d8-8ce73a869bb3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8daf5756-534b-4c34-992b-ce50f6c58c12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/4. Login with empty username and valid password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6826ae40-05b3-4662-a68d-d3c2eb06600d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1258622-926e-4968-a99d-71c32029a127</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40f57cb4-db0f-43aa-aafc-01259b946f8c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43c52c8e-945d-405e-b71c-9bc3c01a99e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/5. Login with empty username and empty password</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0caac2b-cdce-4f60-a248-0b2536faa7f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>576ca9b2-b016-4ef1-8d62-410fd6b7dd7e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>de84975b-7e50-45ee-9771-312160182df7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a08a324a-8d63-4377-a929-b6e0d548190a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/6. Login -Password should be masked</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b1cf494-570a-406e-8b56-99b78d9d7b34</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84f64658-d162-4943-8b00-b397369a8f1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21ecdf61-3238-4d40-a87b-0f305cbcac3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/7. Login -Handles case sensitive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1627bef-a619-4c3f-841a-b947f55790da</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5989a13b-8755-4bfa-9fce-99a6de6d582f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e36710cb-4da3-4fd5-9c7e-ac43bc1bfcbb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login/8. Login -Authentication</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5f4003e-a54a-42a7-9e96-e1c09bde2299</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d5bc776-7b3c-494d-82a5-ea950998c28d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
