<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>buttonRegister</name>
   <tag></tag>
   <elementGuidId>6b393343-614b-44bb-8d44-154ed06e76ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and @name = 'register']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>2bdd9993-4b7f-40d4-b653-6185bb2f3334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>register</value>
      <webElementGuid>b6cae92a-9124-4c62-bcb7-6bdc970cf6dd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
